import os
import shutil
import random
import streamlit as st
import google.generativeai as genai
import chromadb
from sentence_transformers import SentenceTransformer

# =========================================================
# PAGE CONFIG
# =========================================================
st.set_page_config(
    page_title="Renewable Energy Plant Operations Explainer Bot",
    page_icon="⚡",
    layout="wide"
)

# =========================================================
# CUSTOM CSS
# =========================================================
st.markdown("""
<style>
.main {
    background-color: #0f172a;
}
.big-title {
    font-size: 36px;
    font-weight: 800;
    color: #f8fafc;
}
.sub-text {
    color: #94a3b8;
    font-size: 17px;
}
.card {
    background-color: #111c33;
    padding: 18px;
    border-radius: 14px;
    box-shadow: 0px 4px 16px rgba(0,0,0,0.35);
    margin-bottom: 16px;
    border: 1px solid rgba(148,163,184,0.15);
}
.small-muted {
    color: #94a3b8;
    font-size: 12px;
}
.stButton>button {
    background: linear-gradient(90deg, #22c55e, #06b6d4);
    color: white;
    border-radius: 10px;
    height: 42px;
    font-weight: 700;
    border: none;
}
.stTextArea textarea {
    border-radius: 12px;
}
footer {
    visibility: hidden;
}
</style>
""", unsafe_allow_html=True)

# =========================================================
# SYSTEM PROMPT
# =========================================================
SYSTEM_PROMPT = """
You are a Renewable Energy Plant Operations Explainer Bot for educational awareness and training.

Your job:
- Explain renewable energy concepts in simple terms.
- Explain solar plants, wind plants, grid connection, and safety practices.
- Use retrieved knowledge base context when available.
- If retrieved context is not sufficient, provide a general educational explanation.

Strict rules:
- Only provide educational explanations.
- Do NOT control equipment.
- Do NOT provide operational control instructions.
- Do NOT predict or forecast energy output.
- Do NOT provide unsafe wiring, switching, or equipment handling steps.

Style:
- Keep answers simple and structured.
- Use short headings and bullet points.
- Add a short safety note when relevant.
"""

# =========================================================
# KNOWLEDGE BASE
# =========================================================
KB_STATEMENTS = [
    "Renewable energy refers to energy obtained from natural sources that are continuously replenished, such as sunlight, wind, water, and geothermal heat.",
    "Renewable energy sources are considered sustainable because they naturally regenerate over time.",
    "Renewable energy systems help reduce dependence on fossil fuels such as coal, oil, and natural gas.",
    "Renewable energy supports sustainability and can reduce greenhouse gas emissions.",
    "The main goal of renewable energy systems is to generate usable power with lower environmental impact.",

    "The major types of renewable energy include solar energy, wind energy, hydroelectric power, geothermal energy, and biomass energy.",
    "Solar energy is generated by converting sunlight into electricity using photovoltaic technology.",
    "Wind energy is produced when turbines convert the kinetic energy of moving air into electrical energy.",
    "Hydropower uses flowing or falling water to rotate turbines connected to generators.",
    "Geothermal energy uses heat from beneath the Earth's surface for electricity generation or heating.",
    "Biomass energy is produced from organic materials such as wood, crop waste, and biofuels.",

    "Renewable energy sources produce little or no greenhouse gas emissions compared with fossil fuels.",
    "Renewable energy resources are naturally replenished and do not run out like fossil fuels.",
    "Renewable energy can reduce air pollution and environmental damage.",
    "Renewable energy technologies can create employment in engineering, installation, operations, and maintenance.",
    "Renewable energy can improve energy security by reducing dependence on imported fuels.",

    "Some renewable energy sources depend on weather conditions such as sunlight and wind availability.",
    "The initial installation cost of renewable energy systems can be higher than some conventional systems.",
    "Renewable energy systems may require storage or backup solutions for stable power supply.",
    "Large renewable energy projects may require significant land area or supporting infrastructure.",
    "Renewable energy systems require proper grid integration for reliable operation.",

    "Solar photovoltaic panels convert sunlight into direct current electricity using semiconductor cells.",
    "Photovoltaic cells generate electricity when sunlight excites electrons in semiconductor materials.",
    "PV strings combine multiple solar panels in series to increase voltage.",
    "Parallel connections in solar systems increase current capacity.",
    "Combiner boxes collect output from multiple solar strings before power flows to inverters.",
    "Inverters convert direct current electricity from solar panels into alternating current electricity.",
    "Maximum Power Point Tracking helps an inverter operate a solar array near its most efficient point.",
    "Step-up transformers increase voltage so electricity can travel efficiently over long distances.",
    "Switchgear is used for isolation, protection, and safe control of electrical sections in a solar plant.",
    "Grounding or earthing helps reduce electric shock risk and protect equipment during faults.",
    "Surge protection devices help protect solar equipment from lightning and transient surges.",
    "Solar irradiance, temperature, and shading can affect solar plant performance.",
    "PV arrays can generate electricity whenever illuminated, even if the grid is unavailable.",
    "DC arcs can be hazardous, so proper connectors and inspections are important in solar systems.",
    "Thermal hotspots in solar panels can indicate faults, dirt buildup, or shading issues.",
    "String-level monitoring helps identify underperforming sections in a solar plant.",
    "Inverter rooms require ventilation and controlled access because of electrical and thermal risks.",
    "Cable management reduces wear, damage, and accidental disconnection in solar plants.",
    "Ground fault detection helps identify leakage currents that may create electrical hazards.",
    "Solar plant maintenance includes cleaning, inspection, and safety compliance procedures.",

    "Wind turbines convert the kinetic energy of moving air into mechanical rotation.",
    "Rotor blades capture wind energy and transfer motion to the main shaft.",
    "The nacelle contains important turbine components such as the gearbox, generator, and control systems.",
    "A generator converts mechanical rotation into electrical energy.",
    "Some wind turbines use gearboxes to increase rotational speed before generation.",
    "Direct-drive wind turbines reduce the need for gearboxes by connecting the rotor more directly to the generator.",
    "Pitch control changes blade angle to regulate turbine performance and protection.",
    "Yaw control turns the nacelle so the rotor faces the wind direction.",
    "Wind turbine power output is often conditioned by power electronics before grid connection.",
    "A wind farm consists of multiple turbines connected through collection circuits.",
    "Wind farms typically connect to a substation before delivering electricity to the grid.",
    "Wind turbines have cut-in and cut-out wind speed ranges for safe operation.",
    "SCADA systems are used to monitor wind farm status, alarms, and performance data.",
    "Lightning protection is important for wind turbines because they are tall exposed structures.",
    "Wind turbine towers and nacelles present working-at-height and confined-space risks.",
    "Blade inspection and repair require trained personnel due to height and material hazards.",
    "High winds can make climbing and maintenance unsafe in wind farms.",
    "Icing conditions can create thrown-ice hazards near wind turbines.",
    "Hydraulic systems in wind turbines require careful monitoring for leaks and pressure safety.",
    "Mechanical hazards in wind turbines include rotating parts, pinch points, and moving assemblies.",

    "Grid synchronization ensures generated alternating current matches grid voltage, frequency, and phase before connection.",
    "Transmission lines carry high-voltage electricity over long distances.",
    "Distribution networks deliver electricity at lower voltages to homes, schools, and industries.",
    "Substations use transformers, relays, and breakers to regulate and protect electrical flow.",
    "Circuit breakers interrupt abnormal current flow during electrical faults.",
    "Protective relays detect unsafe or abnormal electrical conditions in the power system.",
    "Disconnect switches or isolators provide visible separation for maintenance safety.",
    "Power factor affects how efficiently electrical power is used in the grid.",
    "Interconnection standards may require anti-islanding protection in renewable systems.",
    "Energy meters measure power generated, transmitted, or consumed in the system.",

    "Safety in renewable energy plants depends on training, supervision, and adherence to procedures.",
    "Lockout Tagout procedures help prevent accidental energization during maintenance work.",
    "Personal Protective Equipment may include helmets, gloves, safety shoes, goggles, and insulated gear.",
    "Electrical hazards include electric shock, arc flash, and arc blast.",
    "Only authorized personnel should enter high-voltage areas such as substations and switchyards.",
    "Permit-to-work systems help ensure hazards are identified before work begins.",
    "Emergency response plans define actions for fire, electrical faults, severe weather, and medical incidents.",
    "Fire safety includes extinguisher access, alarm systems, and clear emergency exits.",
    "Good housekeeping reduces trip hazards and improves access to safety equipment.",
    "Insulated tools can reduce electrical risk during approved maintenance activities.",
    "Working at heights requires fall protection and rescue planning.",
    "Confined space procedures are important in enclosed or restricted work areas.",
    "Weather monitoring supports safer outdoor planning in renewable energy sites.",
    "Near-miss reporting helps improve long-term safety culture.",
    "Safety signage and hazard labels help workers identify dangerous and restricted areas."
]

SUGGESTED_QUESTIONS = [
    "What is renewable energy?",
    "What are the types of renewable energy?",
    "What are the advantages and disadvantages of renewable energy?",
    "What is the role of an inverter in solar systems?",
    "How does a solar power plant work?",
    "What are the main parts of a wind turbine?",
    "How does electricity reach homes from renewable plants?",
    "What is grid synchronization?",
    "What safety measures are followed in renewable energy plants?"
]

CHROMA_PATH = "chroma_store"
COLLECTION_NAME = "renewable_energy_kb"

# =========================================================
# SESSION STATE
# =========================================================
if "history" not in st.session_state:
    st.session_state.history = []

if "selected_question" not in st.session_state:
    st.session_state.selected_question = ""

# =========================================================
# LOCAL EMBEDDING MODEL
# =========================================================
@st.cache_resource
def load_embedding_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

def local_embed_texts(texts):
    model = load_embedding_model()
    return model.encode(texts).tolist()

def reset_vector_db():
    if os.path.exists(CHROMA_PATH):
        shutil.rmtree(CHROMA_PATH)

def init_vector_db():
    client = chromadb.PersistentClient(path=CHROMA_PATH)
    collection = client.get_or_create_collection(name=COLLECTION_NAME)

    if collection.count() == 0:
        ids = [f"kb_{i}" for i in range(len(KB_STATEMENTS))]
        embeddings = local_embed_texts(KB_STATEMENTS)

        collection.add(
            ids=ids,
            documents=KB_STATEMENTS,
            embeddings=embeddings,
            metadatas=[{"index": i, "source": "knowledge_base"} for i in range(len(KB_STATEMENTS))]
        )

    return collection

def retrieve_context(collection, query, top_k=5):
    query_embedding = local_embed_texts([query])[0]

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=["documents", "distances", "metadatas"]
    )

    docs = results.get("documents", [[]])[0]
    distances = results.get("distances", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]

    return list(zip(docs, distances, metadatas))

# =========================================================
# SIDEBAR
# =========================================================
with st.sidebar:
    st.markdown("## ⚡ Renewable Energy AI")
    st.markdown("---")

    st.markdown("### ✅ Project Modules")
    st.markdown("""
- Knowledge Base
- Gemini LLM
- Prompt Parameters
- RAG with ChromaDB
- Local Embeddings
- Streamlit App
    """)

    st.markdown("---")
    api_key = st.text_input("🔑 Enter Gemini API Key", type="password")

    st.markdown("### 🎛 Parameters")
    temperature = st.slider("Temperature", 0.0, 1.0, 0.3, 0.05)
    top_p = st.slider("Top-p", 0.1, 1.0, 0.9, 0.05)
    max_tokens = st.slider("Max Output Tokens", 128, 2048, 700, 64)

    st.markdown("### 📚 RAG Settings")
    top_k_ctx = st.slider("Top-k Retrieved Chunks", 2, 10, 5, 1)
    fallback_threshold = st.slider("Fallback Distance Threshold", 0.1, 2.0, 1.2, 0.1)

    st.markdown("---")
    st.caption("Embedding model: all-MiniLM-L6-v2 (local)")

    if st.button("🗑 Clear History"):
        st.session_state.history = []
        st.success("History cleared!")

    if st.button("♻ Reset Vector DB"):
        reset_vector_db()
        st.success("Vector DB reset successfully. It will rebuild on next query.")

# =========================================================
# HEADER
# =========================================================
st.markdown(
    '<div class="big-title">⚡ Renewable Energy Plant Operations Explainer Bot</div>',
    unsafe_allow_html=True
)
st.markdown(
    '<div class="sub-text">RAG-enabled educational chatbot using Gemini + ChromaDB + Streamlit.</div>',
    unsafe_allow_html=True
)
st.markdown("<br>", unsafe_allow_html=True)

col1, col2 = st.columns([2, 1])

# =========================================================
# LEFT COLUMN
# =========================================================
with col1:
    st.markdown('<div class="card">', unsafe_allow_html=True)

    user_input = st.text_area(
        "💬 Enter your question:",
        value=st.session_state.selected_question,
        height=120
    )

    if st.button("⚡ Generate Explanation"):
        if not api_key:
            st.warning("Please enter your Gemini API key in the sidebar.")
        elif not user_input.strip():
            st.warning("Please enter a question.")
        else:
            try:
                collection = init_vector_db()
                retrieved = retrieve_context(collection, user_input.strip(), top_k_ctx)

                use_kb = False
                context_block = ""

                if retrieved:
                    best_distance = retrieved[0][1]
                    if best_distance <= fallback_threshold:
                        use_kb = True
                        context_block = "\n".join([f"- {doc}" for doc, dist, meta in retrieved])

                genai.configure(api_key=api_key)

                model = genai.GenerativeModel(
                    model_name="gemini-2.5-flash",
                    generation_config={
                        "temperature": temperature,
                        "top_p": top_p,
                        "max_output_tokens": max_tokens
                    }
                )

                if use_kb:
                    final_prompt = f"""
{SYSTEM_PROMPT}

Retrieved Knowledge Base Context:
{context_block}

Answer the user's question using the retrieved context.
You may expand slightly with safe general educational explanation if needed.
Do not provide operational control instructions, unsafe actions, or forecasting.

User Question:
{user_input.strip()}
"""
                else:
                    final_prompt = f"""
{SYSTEM_PROMPT}

The retrieved knowledge base context is not sufficient for grounding this query.
Provide a safe general educational explanation.
Do not provide operational control instructions, unsafe actions, or forecasting.

User Question:
{user_input.strip()}
"""

                with st.spinner("Generating response..."):
                    response = model.generate_content(final_prompt)

                answer_text = getattr(response, "text", "").strip()
                if not answer_text:
                    answer_text = "No response generated."

                st.session_state.history.append({
                    "question": user_input.strip(),
                    "answer": answer_text,
                    "sources": retrieved,
                    "used_kb": use_kb
                })

                st.session_state.selected_question = ""
                st.rerun()

            except Exception as e:
                st.error("Error generating response.")
                st.exception(e)

    st.markdown('</div>', unsafe_allow_html=True)

    for item in reversed(st.session_state.history):
        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown(f"**🙋 You:** {item['question']}")
        st.markdown("---")
        st.markdown(f"**🤖 AI:** {item['answer']}")

        if item["used_kb"]:
            st.caption("Response mode: RAG + Knowledge Base")
        else:
            st.caption("Response mode: General educational fallback")

        with st.expander("📌 Retrieved Context"):
            if item["sources"]:
                for doc, dist, meta in item["sources"]:
                    st.markdown(
                        f"- {doc}\n\n<span class='small-muted'>distance: {dist:.4f} | meta: {meta}</span>",
                        unsafe_allow_html=True
                    )
            else:
                st.write("No retrieved context found.")

        st.markdown('</div>', unsafe_allow_html=True)

# =========================================================
# RIGHT COLUMN
# =========================================================
with col2:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown("### 💡 Smart Suggestions")

    for question in random.sample(SUGGESTED_QUESTIONS, min(5, len(SUGGESTED_QUESTIONS))):
        if st.button(question, key=f"suggest_{question}"):
            st.session_state.selected_question = question
            st.rerun()

    st.markdown('</div>', unsafe_allow_html=True)

st.markdown("---")
st.markdown(
    "<center style='color: gray;'>Built with Gemini 2.5 Flash + ChromaDB + Local Embeddings + Streamlit 🚀</center>",
    unsafe_allow_html=True
)